
services:
  - type: web
    name: ecotours-api
    env: node
    buildCommand: cd src/backend && npm install && npm run build
    startCommand: cd src/backend && node dist/main.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 1d
      - key: PORT
        value: 3000
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
    buildFilter:
      paths:
        - src/backend/**
